from typing import Literal

class RawOutputStream:
    def __init__(
        self,
        *,
        device: int | str | None,
        samplerate: int,
        channels: int,
        dtype: Literal["int16"],
    ) -> None: ...
    def start(self) -> None: ...
    def write(self, data: bytes) -> bool: ...
    def abort(self) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...
